name: Build Windows Installer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download Inno Setup
        run: |
          curl -L -o innosetup.exe https://jrsoftware.org/download.php/is.exe
          Start-Process -Wait -FilePath innosetup.exe -ArgumentList '/VERYSILENT /SUPPRESSMSGBOXES /NORESTART'
        shell: pwsh

      - name: Compile Windows installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "HabitOS-windows-setup.iss"
        shell: pwsh

      - name: Upload .exe
        uses: actions/upload-artifact@v4
        with:
          name: Install-HabitOS-Windows
          path: Output/Install-HabitOS.exe
